### ISSUE TITLE
Failure on CMASI.xml.

### ISSUE THREAD

**Issue by chaosape** [gancherj/clmcp#1]
The mdm models used by OpenUxAS reside in the top-level  "mdms" directory of the OpenUxAS repository. When running clmcp on the file "CMASI.xml" from that directory I receive the following error:

> dacosta@morningstar-~/repos/OpenUxAS/mdms-$ python3 ../../clmcp/py/main.py --dir outputdir --mdm CMASI.xml 
> Traceback (most recent call last):
>   File "../../clmcp/py/main.py", line 65, in <module>
>     emit(output_dir, in_file)
>   File "../../clmcp/py/main.py", line 21, in emit
>     mdm = MDM.MDM(filename)
>   File "/home/dacosta/repos/clmcp/py/MDM.py", line 231, in __init__
>     self.structs[i].fillkinds(self)
>   File "/home/dacosta/repos/clmcp/py/MDM.py", line 132, in fillkinds
>     field.fillkind(mdm)
>   File "/home/dacosta/repos/clmcp/py/MDM.py", line 80, in fillkind
>     self.id = struct.id

**Comment by gancherj** [comment]
I hadn't yet fully tested the library -- now that there is interest, I'll make sure it works with CMASI.

**Comment by gancherj** [comment]
OK, it builds now. Let me know if you have any more issues using it.
